# ansible/playbook.yml
---
- hosts: localhost
  become: yes
  tasks:
    - name: Stop current application
      command: systemctl stop tomcat.service
      ignore_errors: yes

    - name: Copy new WAR file
      copy:
        src: /var/lib/jenkins/workspace/jenkins-ansible configuration/target/petclinic.war
        dest: /opt/tomcat/webapps

    - name: Start application
      command: systemctl start tomcat.service
